### ISSUE TITLE
The entrypoint script hogs the CPU

### ISSUE THREAD

**Issue by hgeorgsch** [QuadStingray/docker-webtrees#1]
The idle loop at the end of the entrypoint script loads the CPU 100%. If such an idle loop is necessary, it should do sleep 60 or something similar, to avoid loading the CPU.

Now, I do not understand why apache runs in the background.  I would have thought that you can run trap before apache, and then apache in the foreground.  Maybe the loop is not required at all.  I am not that familiar though, with the apache server process nor the Bourne shell use of trap.

**Comment by hgeorgsch** [comment]
It seems to work fine to run apache in the foreground, after the trap. However, this was not the only change I had to make to make it work, and I will therefore not make a pull request.  If you want to copy my changes, the fork is at https://github.com/hgeorgsch/docker-webtrees

Essentially three changes: docker-compose file, the entrypoint script as discussed above, and added ImageMagick

**Comment by QuadStingray** [comment]
Thanks by fixing this issue.
I merged your fixes into the master.

**Comment by QuadStingray** [comment]
Now there are separate images with the installed vesta plugins: [2.0.7-vesta](https://hub.docker.com/layers/quadstingray/webtrees/2.0.7-vesta/images/sha256-bdffe312b065a5340e25af1a90412da1f93862ca8924df8a34f5bdfe85780484?context=repo) and [latest-vesta](https://hub.docker.com/layers/quadstingray/webtrees/latest-vesta/images/sha256-68f176b92bfda8e8b91a522bc7d171a9ae08eb4a26867da82ef1a5c4fbaff173?context=repo)
